// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/timers.h" 
#include "freertos/event_groups.h"

#include "esp_log.h"
#include "../app/task_flags.h"
#include <stdio.h>
#include "../app/app_max30102.h"
#include "../app/app_uvc_camera.h"
#include "../app/audio.h"
#include "usb_stream.h"
#include "esp_task_wdt.h"
static const char *TAG = "ui_events"; 
extern EventGroupHandle_t task_event_group;

extern TimerHandle_t timer; 

void basicPrac(lv_event_t * e)
{
	// Your code here
}

void speechTask(lv_event_t * e)
{
	// Your code here
}

//开始调用三个任务
/*血氧传感器每次启动记录10个数据。每次之间间隔3s
摄像头每隔5s调用一次回调函数，传递一张图片到后端
音频数据是当1MB的缓冲区填满，传递一次数据到后端*/
// void start_tasks(lv_event_t * e)
// {
//     // Your code here
//     // _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
//     xTaskCreate(max30102_update_task, "max30102_update_task", 8 * 1024, NULL, 5, &max30102_task_handle);
//     xTaskCreate(camera_task, "Camera Task", 16384, NULL, 5, &camera_task_handle);
//     xTaskCreatePinnedToCore(audio_feed_task, "Feed Task", 8 * 1024, NULL, 5, &audio_task_handle, 1);
// }


// // 结束删除三个任务
// void delete_tasks() {
//     // 删除 max30102_task
//     if (max30102_task_handle != NULL) {
//         ESP_LOGI(TAG, "Deleting max30102 task");
//         max30102_task_running = false;   // 设置标志以停止任务中的循环
//         vTaskDelay(pdMS_TO_TICKS(100));  // 确保任务有足够时间清理资源
//         vTaskDelete(max30102_task_handle);
//         max30102_task_handle = NULL;
//     }

//     // 删除 camera_task
//     if (camera_task_handle != NULL) {
//         ESP_LOGI(TAG, "Deleting camera task");
//         camera_task_running = false;     // 设置标志以停止任务中的循环
//         if (timer != NULL) {
//             xTimerStop(timer, portMAX_DELAY);   // 停止计时器
//             xTimerDelete(timer, portMAX_DELAY); // 删除计时器
//             timer = NULL;
//         }
//         usb_streaming_stop();            // 停止 USB 流
//         vTaskDelay(pdMS_TO_TICKS(100));  // 确保任务有足够时间清理资源
//         vTaskDelete(camera_task_handle);
//         camera_task_handle = NULL;
//     }

//     // 删除 audio_task
//     // if (audio_task_handle != NULL) {
//     //     ESP_LOGI(TAG, "Deleting audio task");
//     //     audio_task_running = false;      // 设置标志以停止任务中的循环
//     //     vTaskDelay(pdMS_TO_TICKS(100));  // 确保任务有足够时间清理资源
//     //     vTaskDelete(audio_task_handle);
//     //     audio_task_handle = NULL;
//     // }
// }

// void some_function_to_delete_tasks(lv_event_t * e) {
//     // 需要删除任务时调用
//     delete_tasks();
// }

void start_tasks(lv_event_t * e)
{
    ESP_LOGI(TAG, "Starting all tasks");
    // 设置事件组，启动任务
    xEventGroupSetBits(task_event_group, TASK_START_BIT);
}

void stop_tasks(lv_event_t * e)
{
    ESP_LOGI(TAG, "Stopping all tasks");
    // 清除事件组，暂停任务
    xEventGroupClearBits(task_event_group, TASK_START_BIT);
}

void some_function_to_delete_tasks(lv_event_t * e) {
    // 停止任务时调用
    stop_tasks(e);
}

void some_function_to_start_tasks(lv_event_t * e) {
    // 启动任务时调用
    start_tasks(e);
}