// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"  // 包含 LVGL 头文件

// 函数声明
void basicPrac(lv_event_t * e);
void speechTask(lv_event_t * e);
void start_tasks(lv_event_t * e);
void stop_tasks(lv_event_t * e);
void some_function_to_delete_tasks(lv_event_t * e);
void some_function_to_start_tasks(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* _UI_EVENTS_H */